parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     uvweb_test_doctorat
    database_user:     root
    database_password: ~

    mailer_transport:  gmail
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~
    mailer_encryption: ssl

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt

#CAS UTC
    cas_login_url:                      https://cas.utc.fr/cas/login
    cas_service_validate_url:           https://cas.utc.fr/cas/serviceValidate