jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity: { class: Uvweb\UvBundle\Entity\User, property: login}

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/sflogout, roles: ROLE_USER }
        - { path: ^/sflogin, roles: ROLE_USER }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: uvweb_login
                check_path: sf_login
            logout:
                path:       sf_logout
                target:     /

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
