jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Uvweb\UvBundle\Entity\User, property: identity}

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/logout, roles: ROLE_USER }
        - { path: ^/sflogin, roles: ROLE_USER }
        - { path: ^/post, roles: ROLE_USER }
        - { path: ^/user/edit, roles: ROLE_USER }
        - { path: ^/migration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgottenaccount, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: uvweb_login
                check_path: sf_login
            logout:
                path:       uvweb_logout
                target:     /

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
