uvweb_uv_list:
    path: /uv/all/{order}
    defaults:  { _controller: UvwebUvBundle:Detail:listAll, order: 'name' }
    requirements:
        order: "name|rate"

uvweb_uv_nameslike:
    path: /uv/like
    defaults: { _controller: UvwebUvBundle:Home:getUvNamesLike }

uvweb_uv_detail:
    path: /uv/{uvname}
    defaults:  { _controller: UvwebUvBundle:Detail:detail, uvname: '' }

uvweb_uv_newpost:
    path: /post/{uvname}
    defaults:  { _controller: UvwebUvBundle:Detail:post }

uvweb_uv_uvtitlefetcher:
    path: /uv/titlefetcher
    defaults:  { _controller: UvwebUvBundle:Detail:uvTitle }

uvweb_uv_uvnametoid:
    path: /uv/uvnametoid
    defaults:  { _controller: UvwebUvBundle:Detail:uvNametoUvId }

uvweb_uv_pollsemestertoyear:
    path: /uv/pollsemestertoyear
    defaults:  { _controller: UvwebUvBundle:Detail:pollSemesterToYear }

uvweb_uv_search:
    path: /uv/search/{searchtext}
    defaults:  { _controller: UvwebUvBundle:Detail:search }

uvweb_uv_applist:
    path: /uv/app/list
    defaults:  { _controller: UvwebUvBundle:Detail:appList }

uvweb_uv_appdetail:
    path: /uv/app/{uvname}
    defaults:  { _controller: UvwebUvBundle:Detail:appDetail }
    requirements:
        uvname:  ^[a-zA-Z]{2}+[0-9]{2}$

uvweb_uv_homepage:
    pattern:  /
    defaults: { _controller: UvwebUvBundle:Home:index }

uvweb_uv_appfeed:
    path: /uv/app/newsfeed
    defaults:  { _controller: UvwebUvBundle:Home:appNewsfeed }

#Profile paths
uvweb_uv_profile:
    pattern: /user/{userid}
    defaults: { _controller: UvwebUvBundle:Profile:display }
    requirements:
        userid:  ^[0-9]+$

uvweb_login:
    pattern: /login
    defaults: { _controller: UvwebUvBundle:Profile:login }

uvweb_migration:
    pattern: /migration
    defaults: { _controller: UvwebUvBundle:Profile:migration }

uvweb_user_add:
    pattern: /user/register
    defaults: { _controller: UvwebUvBundle:Profile:addUser }

uvweb_user_edit:
    pattern: /user/edit/{userid}
    defaults: { _controller: UvwebUvBundle:Profile:editUser }
    requirements:
        userid: \d+


#Admin paths
uvweb_admin_home:
    pattern: /admin
    defaults: { _controller: UvwebUvBundle:Admin:home }

uvweb_admin_comment_validate:
    pattern: /admin/validatecomment/{commentid}
    defaults: { _controller: UvwebUvBundle:Admin:validateComment }
    requirements:
        commentid: \d+

uvweb_admin_comment_refuse:
    pattern: /admin/refusecomment/{commentid}
    defaults: { _controller: UvwebUvBundle:Admin:refuseComment }
    requirements:
        commentid: \d+

uvweb_admin_add_news:
    pattern: /admin/news/add
    defaults: { _controller: UvwebUvBundle:Admin:addNews }

uvweb_admin_edit_news:
    pattern: /admin/news/edit/{newsid}
    defaults: { _controller: UvwebUvBundle:Admin:editNews }
    requirements:
        newsid: \d+

uvweb_admin_delete_news:
    pattern:   /admin/news/delete/{newsid}
    defaults:  { _controller: UvwebUvBundle:Admin:deleteNews }
    requirements:
        newsid: \d+

#Authentication paths

sf_login:
    pattern: /sflogin

uvweb_logout:
    pattern: /logout