#Web Service paths
uvweb_uv_applist:
    path: /uv/app/list
    defaults:  { _controller: UvwebUvBundle:Detail:appList }

uvweb_uv_appdetail:
    path: /uv/app/{uvname}
    defaults:  { _controller: UvwebUvBundle:Detail:appDetail }
    requirements:
        uvname:  ^[a-zA-Z]{2}+[0-9]{2}$

uvweb_uv_appfeed:
    path: /uv/app/newsfeed
    defaults:  { _controller: UvwebUvBundle:Home:appNewsfeed }

#In progress
uvweb_uv_catalog:
    path: /uv/catalog
    defaults:  { _controller: UvwebUvBundle:Detail:catalog}

#Setting uv definitions
uvweb_uv_setuvdefinitions:
    path: /setuvdefinitions
    defaults:  { _controller: UvwebUvBundle:Home:setUvDefinitions }

#Old paths
uvweb_uv_uvnametoid:
    path: /uv/uvnametoid
    defaults:  { _controller: UvwebUvBundle:Detail:uvNametoUvId }

uvweb_uv_uvtitlefetcher:
    path: /uv/titlefetcher
    defaults:  { _controller: UvwebUvBundle:Detail:uvTitle }

uvweb_uv_pollsemestertoyear:
    path: /uv/pollsemestertoyear
    defaults:  { _controller: UvwebUvBundle:Detail:pollSemesterToYear }

uvweb_uv_search:
    path: /uv/search/{searchtext}
    defaults:  { _controller: UvwebUvBundle:Detail:search }