uvweb_uv_detail:
    path: /uv/{uvname}
    defaults:  { _controller: UvwebUvBundle:Uv:detail}
    requirements:
        uvname:  ^[a-zA-Z]{2}+[0-9]{2}$
uvweb_uv_uvtitlefetcher:
    path: /uv/titlefetcher
    defaults:  { _controller: UvwebUvBundle:Uv:uvTitle}
uvweb_uv_uvnametoid:
    path: /uv/uvnametoid
    defaults:  { _controller: UvwebUvBundle:Uv:uvNametoUvId}
uvweb_uv_pollsemestertoyear:
    path: /uv/pollsemestertoyear
    defaults:  { _controller: UvwebUvBundle:Uv:pollSemesterToYear}
uvweb_uv_search:
    path: /uv/search/{searchtext}
    defaults:  { _controller: UvwebUvBundle:Uv:search}
uvweb_uv_applist:
    path: /uv/app/list
    defaults:  { _controller: UvwebUvBundle:Uv:appList}
uvweb_uv_appdetail:
    path: /uv/app/{uvname}
    defaults:  { _controller: UvwebUvBundle:Uv:appDetail}
    requirements:
        uvname:  ^[a-zA-Z]{2}+[0-9]{2}$
uvweb_uv_homepage:
    pattern:  /
    defaults: { _controller: UvwebUvBundle:Home:index }