uvweb_uv_detail:
    path: /{uvname}
    defaults:  { _controller: UvwebUvBundle:Uv:detail}
    requirements:
        uvname:  ^[a-zA-Z]{2}+[0-9]{2}$
uvweb_uv_uvtitlefetcher:
    path: /titlefetcher
    defaults:  { _controller: UvwebUvBundle:Uv:uvTitle}
uvweb_uv_uvnametoid:
    path: /uvnametoid
    defaults:  { _controller: UvwebUvBundle:Uv:uvNametoUvId}