parameters:
#    uvweb_uv.example.class: Uvweb\UvBundle\Example

services:
#    uvweb_uv.example:
#        class: %uvweb_uv.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    uvweb_uv.fbmanager:
        class: Uvweb\UvBundle\Services\FlashbagManager\UvwebFlashbagManager
        arguments: [@session]
        scope: request
