parameters:
#    uvweb_uv.example.class: Uvweb\UvBundle\Example

services:
#    uvweb_uv.example:
#        class: %uvweb_uv.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
