Uvweb\UvBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: [email], message: Email déjà enregistré sur le site. }
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields:[identity], message: Pseudo déjà pris. }

    properties:
        email:
            - Email:
                message: '{{ value }}: Email non valide.'
                checkMX: true
            - NotBlank:
                message: Une adresse email est requise.
            - Length:
                max: 50
                maxMessage: L'adresse email ne doit pas faire plus de 50 caractères.
        identity:
            - NotBlank: 
                message: Un pseudo est requis.
            - Length:
                max: 32
                maxMessage: Le pseudo ne doit pas faire plus de 32 caractères.
        origin:
            - NotBlank:
                message: Un cursus d'origine est requis.
            - Length:
                max: 20
                maxMessage: Le cursus d'origine ne doit pas faire plus de 20 caractères.
        firstSemester:
            - NotBlank:
                message: Un semestre d'entrée est requis.
        firstYear:
            - NotBlank:
                message: Une année d'entrée est requise.
        branch:
            - NotBlank:
                message: Un cursus est requis.
        displayAvatar:
            - NotBlank:
                message: Un choix est requis.

Uvweb\UvBundle\Entity\News:
    properties:
        title:
            - NotBlank:
                message: Un titre est requis.
            - Length:
                max: 100
                maxMessage: Le titre de la news ne doit pas excéder 100 caractères.
        text:
            - NotBlank:
                message: Un contenu est requis.
            - Length:
                max: 1000
                maxMessage: Le contenu de la news ne doit pas excéder 1000 caractères.

Uvweb\UvBundle\Entity\Comment:
    properties:
        comment:
            - NotBlank:
                message: Un commentaire est requis.
            - Length:
                max: 10000
                maxMessage: La limite de caractères a été dépassée (10 000 maximum).
        interest:
            - NotBlank:
                message: L'intérêt est requis.
        passed:
            - NotBlank:
                message: L'obtention est requise.
        utility:
            - NotBlank:
                message: L'utilité est requise.
        globalRate:
            - NotBlank:
                message: Une note est requise.
        workAmount:
            - NotBlank:
                message: La quantité de travail est requise.
        pedagogy:
            - NotBlank:
                message: L'avis sur la pédagogie est requis.
        semester:
            - NotBlank:
                message: Un semestre d'obtention est requis.