Uvweb\UvBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: [email], message: Email déjà enregistré sur le site. }
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields:[identity], message: Pseudo déjà pris. }

    properties:
        email:
            - Email:
                message: '{{ value }}: Email non valide.'
                checkMX: true
            - NotBlank:
                message: Une adresse email est requise.
            - Length:
                max: 50
                maxMessage: L'adresse email ne doit pas faire plus de 50 caractères.
        identity:
            - NotBlank: 
                message: Un pseudo est requis.
        origin:
            - NotBlank:
                message: Un cursus d'origine est requis.

Uvweb\UvBundle\Entity\News:
    properties:
        title:
            - NotBlank:
                message: Un titre est requis.

        text:
            - NotBlank:
                message: Un contenu est requis.

Uvweb\UvBundle\Entity\Comment:
    properties:
        comment:
            - NotBlank:
                message: Un commentaire est requis.